config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root 'products#index'

  resources :products, only: [:index, :show] do
    get 'search', on: :collection
  end

  resources :categories, only: [:show]
  resources :orders, except: [:new, :edit, :update, :destroy ] do 
    get 'confirm', on: :collection
    
    member do
      delete 'cancel'
      post 'pay'
      get 'pay_confirm'
    end
  end

  resource :cart, only: [:show, :destroy] do
    get :checkout
  end

  namespace :admin do
    root 'products#index'
    resources :products, except: [:show]
    resources :vendors, except: [:show]
    resources :categories, except: [:show] do
      put 'sort', on: :collection
    end
  end

  # POST /api/v1/subscribe
  namespace :api do
    namespace :v1 do
      post 'subscribe', to: 'utils#subscribe'
      post 'cart', to: 'utils#cart'
      post 'change_item_num', to: 'utils#change_item_num'
    end
  end
end

app/models/cart.rb
class Cart
  attr_reader :items
  def initialize( items = [])
    @items = items
  end


  def add_sku(sku_id, quantity = 1)
    found = items.find {|item| item.sku_id == sku_id}
    if found
      found.increment!(quantity)
    else
      items << CartItem.new(sku_id, quantity)
    end
  end

  def empty?
    @items.empty?
  end

  def total_price
    # items.map {|item| item.total_price}.sum
    # items.map {|item| item.total_price}.reduce(:+)
    total = items.reduce(0) { |sum, item| sum += item.total_price }
    (Date.today.day == 25 && Date.today.month == 12) ? total * 0.9 : total
  end

  def to_hash
    items = @items.map { |item| {"sku_id" => item.sku_id, 
                                "quantity" => item.quantity} }
    
    {
      "items" => items
    }
  end

  def self.from_hash(hash = nil)
    items = []
    
    if hash && hash["items"]
      items = hash["items"].map { |item|
        CartItem.new(item["sku_id"], item["quantity"])
      }
    end
    
    Cart.new(items)
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!

  def show
  end

  def destroy
    session[:cart_9527] = nil
    redirect_to root_path, notice: "購物車已清空"
  end

  def checkout
    @order = current_user.orders.build
  end
end

app/views/carts/_cart.html.erb
<% if current_cart.empty? %>
  <h1 class="title is-size-6">購物車為空的</h1>
  <%= link_to "繼續選購", root_path, class: "button is-medium" %>
  <% else %>
    <table class="table is-fullwidth" data-controller="items">
      <thead>
        <tr>
          <th>品項</th>
          <th>單價</th>
          <th>數量</th>
          <th>小計</th>
        </tr>
      </thead>
      <tbody >
        <% current_cart.items.each do |item| %>
          <tr  data-sku-id="<%= item.sku_id %>">
            <td><%= item.product.name %> - <%= item.sku.spec %></td>
            <td><%= item.product.sell_price %></td>
            <td>
              <%= link_to  '#', class:"button is-small", data:{val:"-",action:"items#cal"} do %><i class="fas fa-minus fa-sm"></i><% end %>
              <span id="cart_item<%= item.sku_id%>"><%= item.quantity %></span>
              <%= link_to  '#', class:"button is-small", data:{val:"+",action:"items#cal"} do %><i class="fas fa-plus fa-sm"></i><% end %>
            </td>
            <td id="cart_item_total<%= item.sku_id%>"><%= item.total_price %></td>
          </tr>
        <% end %>
      </tbody>
      <tfoot>
        <tr>
          <td colspan="3">總價</td>
          <td data-target="items.total"><%= current_cart.total_price %></td>
        </tr>
      </tfoot>
    </table>
  <%= link_to "繼續選購", root_path, class: "button is-medium" %>
  <%= link_to "準備結帳", checkout_cart_path, class: "button is-danger is-medium" %>
    <% end %>

app/views/carts/checkout.html.erb
<section class="container">
  <h1 class="title">結帳</h1>
  <%= render "carts/cart" %>
  <hr>
  <h2 class="title is-5">收件人資訊</h2>

  <%= form_with(model: @order) do |form| %>
    <div class="columns">
      <div class="column">
        <div class="field">
          <%= form.label :recipient, '收件人', class: "label" %>
          <%= form.text_field :recipient, class: "input is-medium"%>
        </div>
      </div>
      <div class="column">
        <div class="field">
          <%= form.label :tel, '電話', class: "label" %>
          <%= form.text_field :tel, class: "input is-medium"%>
        </div>
      </div>
      <div class="column">
        <div class="field">
          <%= form.label :address, '地址', class: "label" %>
          <%= form.text_field :address, class: "input is-medium"%>
        </div>
      </div>
    </div>

    <div class="field">
      <%= form.label :note, '備註說明', class: "label" %>
      <%= form.text_area :note, class: "textarea is-medium"%>
    </div>

    <div class="field">
      <%= form.submit '使用 Line Pay 結帳', class: "button is-primary is-medium", data: {confirm: "確認送出?"} %>
    </div>
  <% end %>

</section>

app/views/carts/show.html.erb
<section class="container">
  <h1 class="title">購物車
  <%= link_to cart_path, method: :delete, data: { confirm: "確定清空購物車?"}, class:"is-size-5"  do %>
  
    <% unless current_cart.items.empty? %>
      <i class="far fa-trash-alt"></i>
      <span >清空購物車</span>
    <% end %>
  <% end %>
  </h1>

  <%= render partial: "cart" %>
</section>